# Generated by Django 4.1.3 on 2022-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_coupon'),
        ('payment', '0002_transaction_products_transaction_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='products',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.cartitems'),
        ),
    ]
