# Generated by Django 4.1.3 on 2022-12-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_coupon'),
        ('payment', '0003_remove_transaction_products_transaction_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.cartitems'),
        ),
    ]
