# Generated by Django 4.1.3 on 2022-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_transaction_items_transaction_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
